<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <DisableBuildCompression>true</DisableBuildCompression>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.8" PrivateAssets="all" />
        <PackageReference Include="Elsa.Studio" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Core.BlazorWasm" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.DomInterop" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Shell" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Authentication.Abstractions" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Authentication.ElsaIdentity.BlazorWasm" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Authentication.ElsaIdentity.UI" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Authentication.OpenIdConnect.BlazorWasm" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Login" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Login.BlazorWasm" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Dashboard" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Localization.BlazorWasm" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Workflows" Version="3.7.0" />
        <PackageReference Include="Elsa.Studio.Workflows.Designer" Version="3.7.0" />
    </ItemGroup>
</Project>
