<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <PackageId>Elsa.Templates</PackageId>
        <Title>Elsa Templates</Title>
        <Description>.NET templates for creating Elsa Server and Elsa Studio solutions.</Description>
        <Authors>Elsa Workflows</Authors>
        <Company>Elsa Workflows</Company>
        <PackageProjectUrl>https://github.com/elsa-workflows/elsa-templates</PackageProjectUrl>
        <RepositoryUrl>https://github.com/elsa-workflows/elsa-templates</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>elsa;workflow;templates;dotnet-new</PackageTags>
        <PackageOutputPath>$(ArtifactsPath)package/$(Configuration.ToLowerInvariant())</PackageOutputPath>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoDefaultExcludes>true</NoDefaultExcludes>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
        <Content Include="templates/**" Pack="true" PackagePath="content/" />
    </ItemGroup>
</Project>
